services:
  server:
    environment:
      SQLALCHEMY_DATABASE_URL: sqlite:////app/static/app.db
      STATIC_FILES: /app/static
      ALLOWED_HOSTS: '["http://localhost:3000"]'
      ALLOWED_METHODS: '["GET","PUT","POST"]'
      ADMIN_KEY: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    image: ghcr.io/sidecuter/statapi:latest
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static
