[project]
name = "stat-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiofiles",
    "alembic",
    "annotated-types",
    "anyio",
    "apscheduler",
    "certifi",
    "click",
    "dnspython",
    "email-validator",
    "fastapi-cli",
    "fastapi-pagination",
    "fastapi",
    "greenlet",
    "h11",
    "httpcore",
    "httptools",
    "httpx",
    "idna",
    "iniconfig",
    "jinja2",
    "mako",
    "markdown-it-py",
    "markupsafe",
    "mdurl",
    "packaging",
    "pluggy",
    "psycopg2-binary",
    "pydantic-core",
    "pydantic-settings",
    "pydantic",
    "pygments",
    "python-dotenv",
    "python-multipart",
    "pyyaml",
    "rich-toolkit",
    "rich",
    "shellingham",
    "sniffio",
    "sqlalchemy",
    "starlette",
    "typer",
    "typing-extensions",
    "uuid",
    "uvicorn",
    "uvloop",
    "watchfiles",
    "websockets",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
lint = [
    "flake8>=7.2.0",
]
