name: Python test

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running tests
        run: pytest

  migrate:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate database scheme
        run: |
          ./create_envfile
          alembic upgrade head
        env:
          SQLALCHEMY_DATABASE_URL=${{secrets.SQLALCHEMY_DATABASE_URL}}

  publish:
    if: github.ref == 'refs/heads/master'
    needs: migrate
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy action on hosting
        run: curl ${{secrets.DEPLOY_HOOK}}
