name: Python test

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install deps
        run: uv sync --dev --frozen
      - name: Run tests
        run: uv run pytest app/tests
